### ISSUE TITLE
your iPhone is not in the supported device list

### ISSUE THREAD

**Issue by akshaypatil4321** [CokePokes/PhantomExo#10]
I did exactly mentioned in the steps. and at the end i get error that your iPhone is not in the list.
I am using iPhone 5 with iOS 10.0.2.

**Comment by DownCh** [comment]
I use iPhone 5 with iOS 10.0.2 and I only download .ipa then skip to step 7.
I installed the .ipa file with iTunes and I see the app load on my device's screen, but when it's completed, the app disappears without any error message.
I don't use CydiaImpactor, how use it ?

**Comment by akshaypatil4321** [comment]
Well you can install cydia impactor from the given link. After that connect your iPhone and go to imapctor and then
First delete snapchat app from ur phone.

Device>>Install Package>> And choose .ipa 

then it will ask you to put your email id and password of App store.

Put your email id with only first letter CAPITAL and then regular password and sit back let the software do its work.

If you don't get error like your iPhone is not in supported device list. Let me know.

**Comment by DownCh** [comment]
I tried twice, and both times I had the same message..
We're in the same sh*t

![capture d ecran 2016-10-06 a 17 14 36](https://cloud.githubusercontent.com/assets/22655649/19158516/52e845d6-8be9-11e6-927f-045abdd5fc49.png)

**Comment by akshaypatil4321** [comment]
Yeah...I am waiting for cokepokes to reply. Already put this on his twitter for 4 times. But didn't get his attention. You can also try. at least will know if we can have some hopes or we just wait for the jailbreak.

**Comment by Critter** [comment]
It's not a CokePokes/Phantom issue.. the issue is with Cydia Impactor. It looks like Impactor doesn't support iphone 5.

**Comment by akshaypatil4321** [comment]
@Critter ohh Do you know which Cydia Impactor can support iphone 5 ??

**Comment by Critter** [comment]
@akshaypatil4321 I do not, but you might ask @saurik on twitter. He might be able to point you in the right direction..

**Comment by akshaypatil4321** [comment]
@Critter Lol...already sent tweet to him. But I don't think he will reply or even read the tweet. :(

**Comment by Critter** [comment]
You *should* be able to re-sign the app yourself using [iOSAppSigner](https://github.com/DanTheMan827/ios-app-signer/releases), and then load it onto your device using the device manager in Xcode

**Comment by akshaypatil4321** [comment]
@Critter I have windows 7. Does it work on it ??

**Comment by Critter** [comment]
@akshaypatil4321 all other methods that I know of would require a mac...

**Comment by CokePokes** [comment]
I'll add iPhone5,2 to the info.plist in the ipa
