### ISSUE TITLE
No Phantom features

### ISSUE THREAD

**Issue by akshaypatil4321** [CokePokes/PhantomExo#13]
Hi..after performing the mentioned step which is installing the provided ipa and then signing through developer site. Snapchat is installed but regular one without the Phantom. Any one facing same issue and can someone who solved it mention about the correct steps?

**Comment by Critter** [comment]
I just installed the 1.0.2 from the download link. (I just skipped to 7..) The Phantom options show up for me. 

I don't know if they would conflict, but did you make sure to delete snapchat before installing the new one?

**Comment by akshaypatil4321** [comment]
Yeah deleted the snapchat first. Then I sign in to developer account and accepted it. Then started with impactor.

**Comment by Critter** [comment]
Anything in the top of settings?
![phantom](https://cloud.githubusercontent.com/assets/73031/19198554/c9fa157e-8c8d-11e6-965e-ffb4bc59852f.png)

if not.. I'd delete and try again. odd that it threw no error or anything, though

**Comment by akshaypatil4321** [comment]
nahh unfortunately not. Also after installation restarted the device but still the same snapchat without phantom :(! I tried it by deleting the complete profile and installed again but no success. 

I got email from the Apple though about revoked certificate. Is it a problem ?

**Comment by Critter** [comment]
They revoked YOUR certificate?

**Comment by akshaypatil4321** [comment]
ohh ok. I will do that

**Comment by akshaypatil4321** [comment]
@Critter Can't make new apple ID. Tried every fucking combination they just don't let me do it :(

**Comment by akshaypatil4321** [comment]
@Critter But whats the revoke certificate thing has to do with phantom ?

**Comment by Critter** [comment]
@akshaypatil4321 did you try with a different email address? when you enter your email/pass into impactor, it's signing the application with that 'free' account. it sounds like they revoked that account ? for one reason or another?

**Comment by akshaypatil4321** [comment]
I tried to make a new Apple ID but without any reason I can't make one!

**Comment by akshaypatil4321** [comment]
@Critter @CokePokes I tried to install snapchat++ with the same way and it worked. But honestly I prefer Phantom all the way. :( Lets hope Cokepokes will fix the issue in the new update.
