### ISSUE TITLE
v1.0.2-1 Unable to login to snapchat

### ISSUE THREAD

**Issue by Critter** [CokePokes/PhantomExo#15]
Just installed the new version, and am unable to login to snapchat. I can create a new account, but when I log out of that account, I am no longer able to log back in. 

It says it cannot connect.

I uninstalled the tweaked version and reinstalled the appstore version and was able to login to my accounts.

**Comment by sikdaz** [comment]
same here

**Comment by instaglen** [comment]
Capitalize the first letter of your username and add a space at the end. Worked for me

**Comment by Critter** [comment]
@instaglen odd.. that still did not work for me

**Comment by Critter** [comment]
@sikdaz @instaglen interestingly enough.. logging in with my username failed, but logging in with my email address worked.

**Comment by akshaypatil4321** [comment]
I think it has to do with developer email id account. I tried with other email it worked. But I am using now SNAPCHAT++

**Comment by instaglen** [comment]
Nope don't think so. Delete the cracked app first. Re-install the original snapchat app via app store. Log in to that app. Delete that. Reinstall this using impactor again. Should be able to log in then

**Comment by Critter** [comment]
This issue was solved with 1.0.3 - Note the new install instructions
