### ISSUE TITLE
ipa.cpp:145

### ISSUE THREAD

**Issue by etshh** [CokePokes/PhantomExo#17]
<img width="418" alt="screen shot 2016-10-08 at 2 52 44 am" src="https://cloud.githubusercontent.com/assets/22408343/19208993/888f4896-8d02-11e6-9ef8-18ef634ecdc4.png">

Is there something I am doing wrong. Downloaded the ipa from the link and sideloaded like i do to all apps.

**Comment by CokePokes** [comment]
Delete the Appstore version first.

**Comment by etshh** [comment]
THANK YOU. Please never give up youre doing a wonderful job
