### ISSUE TITLE
ads/camera

### ISSUE THREAD

**Issue by 2f6y** [CokePokes/PhantomExo#2]
Cant take any photos or use face filters / remove ads not working on iphone 7 ios 10.0.2

**Comment by Nagovitch** [comment]
Having the same problems on iPhone 6 Plus running iOS 10.0.2.

**Comment by mflores777** [comment]
same issue, 7plus 10.0.2

**Comment by nealwin** [comment]
Same issue here 7plus 10.1

**Comment by Vandalysm** [comment]
Same, 7 plus 10.1

**Comment by tekkniq** [comment]
My current issue also

**Comment by CokePokes** [comment]
This issue was fixed in v1.01
