### ISSUE TITLE
Could not connect to server

### ISSUE THREAD

**Issue by topgunsamus** [CokePokes/PhantomExo#28]
Error preventing login to snapchat, checked password and username works on other devices and is able to login.

**Comment by Critter** [comment]
There are instructions in the [ReadMe](https://github.com/CokePokes/PhantomExo/blob/master/README.md) that walk through this.

**Comment by CokePokes** [comment]
@Critter Thanks for letting users know!

**Comment by TitanXV** [comment]
went though that process on latest version (v9.42.2.0with1.5.0 phantom), copied documents and everything. still didnt work
