### ISSUE TITLE
32-Bit devices like iPhone 5

### ISSUE THREAD

**Issue by xC0dex** [CokePokes/PhantomExo#30]
Hey Guys,

for people with 32-bit devices I created a correct Snapchat.ipa with V. 1.0.5.
You can download the full .zip file on http://justinlampe.de/download.php.

**Comment by DownCh** [comment]
https://github.com/CokePokes/PhantomExo/issues/29

Same result, on iPhone 5

**Comment by xC0dex** [comment]
On CokePokes link I got an error that the .ipa only supports 64-bit devices. With his .zip file I don't have the error anymore.

**Comment by akshaypatil4321** [comment]
Thanks for putting the file. But is it phantom supported ? 
Cause I used snapchat++ and got deleted by Snapchat twice. So don't want to do it again..

**Comment by xC0dex** [comment]
Oh :/. I used Phantom now over 3 years without any ban or something like that. In my uploaded file is the newest version of phantom included. :)

**Comment by xC0dex** [comment]
Moreover in my opinion Phantom is much better than Snapchat++, but this is my point of view.

**Comment by DownCh** [comment]
A developer account is required to install this application?

**Comment by DownCh** [comment]
You're my new God

**Comment by akshaypatil4321** [comment]
I fucking Love You man @xC0dex  Now!!!! Just installed it. And its fucking WORKING!!!!!!!!! Thanks a ton!!!!!!!
@CokePokes I love you too for the Awesome work you are doing :) :) :) :100: !

**Comment by DownCh** [comment]
![capture d ecran 2016-10-19 a 21 08 00](https://cloud.githubusercontent.com/assets/22655649/19533474/319872fa-9640-11e6-9c24-50c070164854.png)

**Comment by xC0dex** [comment]
@DownCh What's the problem? I created a new page http://code.justinlampe.de. I think this is a better link. :) 
BTW I'll update my .zip file when CokePokes released a new version of Phantom.

**Comment by DownCh** [comment]
Sorry it was with http://justinlampe.de/download.php thank you for the new link (:

**Comment by akshaypatil4321** [comment]
Awesome man...for helping us out here :))) 

But my Snapchat keep crashing when I open video sent in chat.
Also happeneing with u?

**Comment by xC0dex** [comment]
@akshaypatil4321 I don't sent videos in with Snapchat but I don't have this crash I think :/. Maybe reinstall Snapchat or waiting for an update :/

**Comment by xC0dex** [comment]
@DownCh now the link will redirect to the new URL :)

**Comment by akshaypatil4321** [comment]
No I meant my frnds send me vide in chat and when I open video app crashes. Rest is fine I guess. But u said this is the latest version of phantom right ?

**Comment by xC0dex** [comment]
Yeah, it's the latest version of Phantom. Maybe @CokePokes could look into the bug. I don't have any issues..

**Comment by CokePokes** [comment]
@xC0dex Did you crack this on an armv7 device? Clutch seems to only want to dump the compatible binary depending on device. (Which is why my link is only arm64)

**Comment by xC0dex** [comment]
@CokePokes I downloaded a cracked version of Snapchat and followed your installation-guide. I'm honest, I did norhing special. Idk why but this works without issues.

**Comment by akshaypatil4321** [comment]
Getting error of check connection when tried to log in with another account. And now can not even log in with the first account which was working with phantom :( 
so basically can not log in with either of account. #Helpppp

**Comment by DownCh** [comment]
Same problem, ahah

**Comment by xC0dex** [comment]
@akshaypatil4321 @DownCh this is a known problem. CokePokes already post a link with an alternative option to use Phantom. But this option did'nt work on an 32-Bit device, because the developer used Cokepokes link and rewrite the .ipa file. If you try this with my version, you will get a error-message that the .ipa file is from another account. :/
I fixed the connection-error with this steps, however without a guarantee:
1. Unistall Snapchat wirh Phantom.
2. Install Snapchat from the Appstore and Login.
3. Delete the App and reinstall the .zip file with Impactor. Maybe @CokePokes could release with V 1.0.6 a .ipa file, which is compatible with armv7 devices. :)

**Comment by akshaypatil4321** [comment]
@xC0dex Actually I did the same process as someone mentioned this thing in other issues. But didn;t work.
So I install app through new apple id from impactor and i logged in. But I am not taking risk to log out till @CokePokes fixes the issue.

**Comment by xC0dex** [comment]
I don't know if it's an issue of Phantom..

**Comment by al-muftah** [comment]
Same problem

**Comment by xC0dex** [comment]
This problem is known.. Hope @CokePokes has the possibility to fix this bug with an update. However I'm still not sure if it's a problem of Phantom.

**Comment by DownCh** [comment]
Problem solved for me :
- install snapchat from the AppStore > connect > disconnect ( > sync with iTunes )
- delete snapchat from the AppStore ( > sync with iTunes )
- install Phantom > allow dev in Settings > log on Phantom
This solution works for me

**Comment by akshaypatil4321** [comment]
Did u log out and try to log in after doing that ?

**Comment by DownCh** [comment]
Phantom works like that for me, I have no notification but I prefer Phantom without notification as notifications and no Phantom. 

I think the app from the AppStore on the device left a _"trace"_ that said "this account is already connected" (on Snapchat so), so if you log out before uninstall Snapchat App, the _"trace"_ will gone, and you can connect / disconnect without problem on Phantom.

**Comment by xC0dex** [comment]
@DownCh Great, I will link this on my download-page ok?

**Comment by DownCh** [comment]
As you want @xC0dex there's no © ahah

**Comment by xC0dex** [comment]
@DownCh it works for me too, but without "sync with iTunes". 👍

**Comment by akshaypatil4321** [comment]
Is it only me that who got log out from phantom automatically and can't log in now?

**Comment by DownCh** [comment]
@akshaypatil4321 I don't know if you have the same problem than me but, today I wanted to use Phantom / Snapchat, a message saying "Snapchat is no longer available" was displayed on my screen. I tried to reinstall the @xC0dex 's .ipa except that now the log in problem came back and manipulation that I mentioned a few days ago no longer works...

**Comment by akshaypatil4321** [comment]
Hi...I am having kind of same problem which says that my Snapchat version or device version is nt updated. So please update to use snapchat. 

So maybe by tomorrow when cokepokes puts a updated version for sideload Xcode will give us the 32bit compatible version i hope.

**Comment by xC0dex** [comment]
Hey, have the same problem. Hate Snapchat for this move, you are forced to update the Snapchat.app. As already said, CokePokes will release a compatible version of Phantom tomorrow and I'll update it directly.

**Comment by xC0dex** [comment]
CokePokes updated a link for 32 Bit devices. I'll close this issue!
