### ISSUE TITLE
*Not Issue* Fix Could Not Connect [Snapchat Phantom for iOS 9 & 10]

### ISSUE THREAD

**Issue by Abbasoo** [CokePokes/PhantomExo#36]
Step 1. Delete any versions of sideloaded/Appstore Phantom/Snapchat.
Step 2. Download "Snapchat Sign in" from the link below.
Snapchat Sign in || http://www104.zippyshare.com/v/rnx1Qrpp/file.html
Step 3. Install "Snapchat Sign in" whit Cydia Impactor & Login with your account.
Step 4. KILL Snapchat from background.
Step 5. Download & Install "Snapchat with Phantom" with Cydia Impactor from the link below.
Snapchat with Phantom || http://www104.zippyshare.com/v/ORPN0ZV5/file.html
Step 6. ENJOY!!!

*** Note || Tested & WORKING in iPhone 7Plus Running iOS 10.1 ***

**Comment by 100thewill** [comment]
I followed this but i'm still getting the error.

**Comment by akshaypatil4321** [comment]
U should check if ur account is not deleted. Delete Snapchat with phantom. Install normal Snapchat and check if you can log in. Snapchat deleted my account today. :(

**Comment by Abbasoo** [comment]
@akshaypatil4321 My account is workjing fine.

**Comment by Critter** [comment]
@akshaypatil4321 what are you doing that gets your account deleted so much? I've used Phantom for years on a jailbroken phone, and now on a non-jailbroken phone with no issues to my account...

**Comment by Abbasoo** [comment]
@100thewill Download the original Snapchat from the App Store and try to login. If u can't, then may be Snapchat deleted ur account.

P.S. My account still working fine.

**Comment by akshaypatil4321** [comment]
Actually I was trying to run one account where everyone sends a snap and I upload it 😕 I was able to get 2000 views and then I think some fucker reported my account and Snapchat deleted it. But Snapchat didn't email me about asking app. Is it possible if someone reports it then they just delete the account ??

**Comment by w903413** [comment]
Thanks!!!

**Comment by Legitgamer264** [comment]
I can't sign into phantom. Idk why this hasn't been fixed. The tutorial on the bottom of the page doesn't work and yet he still tells people to use that method

**Comment by Abbasoo** [comment]
@Legitgamer264 You can try this method i posted here.

**Comment by xC0dex** [comment]
@Legitgamer264 look at http://code.justinlampe.de there are 3 installations-guides with the download links above. Moreover at the bottom are Tips. If you follow the steps there, it should work.

**Comment by diolil1234** [comment]
I have a question, if I have two different accounts do I have to do the process over again if I want to switch between the two?

**Comment by Abbasoo** [comment]
@diolil1234 Unfortunately YES.

**Comment by xC0dex** [comment]
@diolil1234 which iPhone do you use?

**Comment by diolil1234** [comment]
@xC0dex I have the iPhone 7 Plus, this method works for me, I tried the way the author has but it didn't work, and did more searching and found this, btw thanks for this method @abbasoo

**Comment by xC0dex** [comment]
@diolil1234 I'm brilliant! You can install 2 Phantoms. 1 App for 1 Account!

**Comment by xC0dex** [comment]
It works for me without connection-error. But I think notifications don't work..

**Comment by diolil1234** [comment]
@xC0dex Yea my notifications don't work but I still connect and that's what I care about, and how do you get the second one!?

**Comment by xC0dex** [comment]
Install Phantom from a GitHub-link (with a changed bundle-id) and install my Phantom version called "Phantom - alt" form my webpage and install it. After that you have installed "Phantom.app" and "Snapchat.app". I use my main account in the "Snapchat.app" and the 2. acc in the "Phantom.app". Both apps are independently of each other. 
Visit http://code.justinlampe.de for the download-link. :)

**Comment by diolil1234** [comment]
Well the only one there that I can download is the one I already used, so how would I find the one with a changed bundle-id? I understand everything else except that first part haha.

**Comment by xC0dex** [comment]
Download 1 version of Phantom from CokePokes links on GitHub and the 2. version from my website. The 4. link (Download Phantom - alt). Now you can install 2 different .zip files, both are working.





On Mon, Oct 31, 2016 at 4:46 PM +0100, "diolil1234" <notifications@github.com> wrote:












Well the only one there that I can download is the one I already used, so how would I find the one with a changed bundle-id? I understand everything else except that first part haha.

**Comment by diolil1234** [comment]
Alright, so download and install the phantom app on my phone, then download and install the one from your website onto my phone, and I'd have the phantom app I already had before doing this, and then another snapchat app that is by itself?

**Comment by diolil1234** [comment]
Alright, so download and install the phantom app on my phone, then download
and install the one from your website onto my phone, and I'd have the
phantom app I already had before doing this, and then another snapchat app
that is by itself?

**Comment by xC0dex** [comment]
Yeah, correct. But you must delete the original Snapchat app for this.

**Comment by Barbie90** [comment]
Happy new year everyone ❣🎉
Snapchat plus log in connection error continues to fail me on iOS 10.2 🤦🏼‍♀️
I'm open to any suggestions 😩
 I don't have jailbreak nor cydia installed . 
And I have not used cydia impactor method . Only zestia newest update to download tweak apps into my iPhone . 
Can anyone help ? 🤦🏼‍♀️
