### ISSUE TITLE
Deleted account after using Phantom

### ISSUE THREAD

**Issue by akshaypatil4321** [CokePokes/PhantomExo#37]
Snapchat deleted My account 4th time. First 3 times it was when I was using snap++. But this time even with phantom they deleted my account. 

Is it possible that if someone reports to my account then Snapchat checks for the 3rd party app? Then delete my account.  ?

**Comment by Abbasoo** [comment]
@akshaypatil4321 Yes, may be ur girlfriend reported u. She dosen't wan't u to save her pictures 🙂.

**Comment by akshaypatil4321** [comment]
Lol.. :(

**Comment by akshaypatil4321** [comment]
@Abbasoo But is it possible like lets say I report your account that u r sending me nudes or something which I don't like. But in real you are not sending me anything. So snapchat would just delete your account ? That's my concern. Because some fucker email me saying that his friend is doing the report thing but I didn't believe him as I was using snap++ for time being. And thought that might be security reason of snap++ I am getting blocked or deleted from snapchat.
But it happened with Phantom too. Do you have any knowledge of this ? If they delete account under false report also without giving u advance notice?

**Comment by Abbasoo** [comment]
@akshaypatil4321 Yes, they can delete ur account with false reports.

**Comment by Legitgamer264** [comment]
Phantom keeps signing me out when I close the app. I can't send messages either. Is this a snapchat or phantom problem?

**Comment by Abbasoo** [comment]
@Legitgamer264 Snapchat server is kicking u out when u are using modified version of snapchat. We have to wait till they find some workaround.

**Comment by Legitgamer264** [comment]
@Abbosoo okay. Thank you. It's also happening with snapchat++
