### ISSUE TITLE
Current version does not load into snapchat.

### ISSUE THREAD

**Issue by bastardsnow** [CokePokes/PhantomExo#38]
Update killed ability to save pictures. No menu access or available options in SC settings. Issue where crash on launch has been resolved but none of the phantom options are available. Confirmed it downloaded properly as tweak access within IOS Settings is still available. 

Attempted:
Reinstall
SC redownload
Phantom downgrade/upgrade

Current IOS: 9.0.2
Device: iPhone 6+

**Comment by Abbasoo** [comment]
@bastardsnow Do u have jailbreak in ur iOS device ?

**Comment by bastardsnow** [comment]
Yes. It is jailbroken and has been working up till the recent SC update.

**Comment by Abbasoo** [comment]
@bastardsnow You can try this #36 . See if it works.

**Comment by bastardsnow** [comment]
Looks like I got it to work. The impactor didn't work either. Which is weird, usually it uploads the packages with no issues. I ended up restoring my device with a 9.0.2 and then re-jailbreaking. Then I re-impacted and we're good to go. Must have been an issue with the package trying to install after the updates. Either way, thank you Abbasoo!
